### ISSUE TITLE
Metrics failures during build don't result in dispatcher shutting down

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-metrics-plugin#16]
This shouldn't happen:

```
Total time: 5.509 secs
Exception in thread "HttpESMetricsDispatcher" java.lang.IllegalStateException: buildId has not been set
    at nebula.plugin.metrics.com.google.common.base.Preconditions.checkState(Preconditions.java:173)
    at nebula.plugin.metrics.dispatcher.AbstractESMetricsDispatcher$1.get(AbstractESMetricsDispatcher.java:48)
    at nebula.plugin.metrics.dispatcher.AbstractESMetricsDispatcher$1.get(AbstractESMetricsDispatcher.java:45)
```

**Comment by DanielThomas** [comment]
I'm closing all open issues because we've adopted Gradle Enterprise and we'll be no longer maintaining this plugin. It was already difficult maintaining compatibility due to internal API use, but Gradle 7 and configuration caching will make keeping this working impossible without a rewrite.
