### ISSUE TITLE
MalformedJsonException when trying to connect to Elasticsearch

### ISSUE THREAD

**Issue by santoshgokak** [nebula-plugins/gradle-metrics-plugin#21]
Below is the trace:

`Exception in thread "HttpESMetricsDispatcher" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at nebula.plugin.metrics.io.searchbox.action.AbstractAction.parseResponseBody(AbstractAction.java:96)
        at nebula.plugin.metrics.io.searchbox.action.AbstractAction.createNewElasticSearchResult(AbstractAction.java:67)
        at nebula.plugin.metrics.io.searchbox.action.GenericResultAbstractAction.createNewElasticSearchResult(GenericResultAbstractAction.java:20)
        at nebula.plugin.metrics.io.searchbox.client.http.JestHttpClient.deserializeResponse(JestHttpClient.java:146)
        at nebula.plugin.metrics.io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:65)
        at nebula.plugin.metrics.dispatcher.HttpESMetricsDispatcher.execute(HttpESMetricsDispatcher.java:109)
        at nebula.plugin.metrics.dispatcher.HttpESMetricsDispatcher.createIndex(HttpESMetricsDispatcher.java:71)
        at nebula.plugin.metrics.dispatcher.AbstractESMetricsDispatcher.initDatastore(AbstractESMetricsDispatcher.java:138)
        at nebula.plugin.metrics.dispatcher.AbstractMetricsDispatcher.startUp(AbstractMetricsDispatcher.java:121)
        at nebula.plugin.metrics.com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:55)
        at nebula.plugin.metrics.com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
        at com.google.gson.JsonParser.parse(JsonParser.java:60)
        ... 13 more
`

**Comment by FuadBalashov** [comment]
@santoshgokak did you manage to fix this?

**Comment by FuadBalashov** [comment]
@santoshgokak try manually creating your index.

**Comment by sjabiulla** [comment]
Did you guys manage to fix this..??  I'm getting the same issue. 

@FuadBalashov  I have an index already created, so I can't create a new index manually on every call. 

Any ideas?

**Comment by FuadBalashov** [comment]
Hey @sjabiulla when I was originally dealing with this problem I could not get it working until I made the new index, after I made it I never ran into issues again. If you already have the index and are running into this problem then I don't have any suggestions.

It has also been a few months since I worked with this so my memory is hazy. If you have anything new to share please do so. Best of luck!

**Comment by DanielThomas** [comment]
Thanks for weighing in @FuadBalashov! We haven't seen anything like this internally.

**Comment by ghost** [comment]
I am also getting the following error (my index is created):

```
:buildSrc:build UP-TO-DATE
Exception in thread "HttpESMetricsDispatcher" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at nebula.plugin.metrics.io.searchbox.action.AbstractAction.parseResponseBody(AbstractAction.java:96)
        at nebula.plugin.metrics.io.searchbox.action.AbstractAction.createNewElasticSearchResult(AbstractAction.java:67)
        at nebula.plugin.metrics.io.searchbox.action.GenericResultAbstractAction.createNewElasticSearchResult(GenericResultAbstractAction.java:20)
        at nebula.plugin.metrics.io.searchbox.client.http.JestHttpClient.deserializeResponse(JestHttpClient.java:146)
        at nebula.plugin.metrics.io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:65)
        at nebula.plugin.metrics.dispatcher.HttpESMetricsDispatcher.execute(HttpESMetricsDispatcher.java:109)
        at nebula.plugin.metrics.dispatcher.HttpESMetricsDispatcher.createIndex(HttpESMetricsDispatcher.java:71)
        at nebula.plugin.metrics.dispatcher.AbstractESMetricsDispatcher.initDatastore(AbstractESMetricsDispatcher.java:121)
        at nebula.plugin.metrics.dispatcher.AbstractMetricsDispatcher.startUp(AbstractMetricsDispatcher.java:118)
        at nebula.plugin.metrics.com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:55)
        at nebula.plugin.metrics.com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
        at com.google.gson.JsonParser.parse(JsonParser.java:60)
        ... 13 more
:testMetrics
```

metrics section in my build.gradle:
```
metrics {
    dispatcherType = 'ES_HTTP'
    hostname = 'hostname'
    httpPort = 80
    indexName = 'metrics-name'
    rollingIndex = false
}
```

I am trying to do this against AWS ESS and the Elasticsearch version is 5.3

I tried to manually load a document using curl and it's working fine.

Thanks,
Steve

**Comment by dvdrlee** [comment]
If you use `--debug` to enable debug logging from the cmd line then you'll see a print out of the http request/response

**Comment by DanielThomas** [comment]
I'm closing all open issues because we've adopted Gradle Enterprise and we'll be no longer maintaining this plugin. It was already difficult maintaining compatibility due to internal API use, but Gradle 7 and configuration caching will make keeping this working impossible without a rewrite.
