### ISSUE TITLE
Plugin Fails with Gradle Composite Project

### ISSUE THREAD

**Issue by sghill** [nebula-plugins/gradle-metrics-plugin#22]
Running a gradle composite build from the command line causes this plugin to fail with the following exception:

```
Caused by: java.lang.IllegalStateException: Expected a wrapped logging output, but instead found nebula.plugin.metrics.collector.LoggingCollector$2@16a73d40
        at nebula.plugin.metrics.collector.LoggingCollector.reset(LoggingCollector.java:123)
        at nebula.plugin.metrics.collector.GradleCollector.shutdownIfComplete(GradleCollector.java:205)
        at nebula.plugin.metrics.collector.GradleCollector.buildFinishedClosure(GradleCollector.java:135)
        at nebula.plugin.metrics.MetricsPlugin$3.doCall(MetricsPlugin.java:126)
```

The build does succeed if the plugin is disabled with `metrics.enabled=false`.

**Comment by DanielThomas** [comment]
I'm closing all open issues because we've adopted Gradle Enterprise and we'll be no longer maintaining this plugin. It was already difficult maintaining compatibility due to internal API use, but Gradle 7 and configuration caching will make keeping this working impossible without a rewrite.
