### ISSUE TITLE
Nebula Metrics with an Android Project

### ISSUE THREAD

**Issue by FuadBalashov** [nebula-plugins/gradle-metrics-plugin#23]
I am trying to add the plugin to a new android project but I keep getting a MalfromedJsonException whenever I sync.

The gradle version of the project: 3.3 (distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip)
android tools gradle plugin: 2.3.0
*For more info see : https://developer.android.com/studio/releases/gradle-plugin.html*

This looks similar to the issue open against this repo [here](https://github.com/nebula-plugins/gradle-metrics-plugin/issues/21)

**Stacktrace**
````
[metrics] Creating index build-metrics-android for metrics
Exception in thread "HttpESMetricsDispatcher" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at nebula.plugin.metrics.io.searchbox.action.AbstractAction.parseResponseBody(AbstractAction.java:96)
	at nebula.plugin.metrics.io.searchbox.action.AbstractAction.createNewElasticSearchResult(AbstractAction.java:67)
	at nebula.plugin.metrics.io.searchbox.action.GenericResultAbstractAction.createNewElasticSearchResult(GenericResultAbstractAction.java:20)
	at nebula.plugin.metrics.io.searchbox.client.http.JestHttpClient.deserializeResponse(JestHttpClient.java:146)
	at nebula.plugin.metrics.io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:65)
	at nebula.plugin.metrics.dispatcher.HttpESMetricsDispatcher.execute(HttpESMetricsDispatcher.java:109)
	at nebula.plugin.metrics.dispatcher.HttpESMetricsDispatcher.createIndex(HttpESMetricsDispatcher.java:71)
	at nebula.plugin.metrics.dispatcher.AbstractESMetricsDispatcher.initDatastore(AbstractESMetricsDispatcher.java:138)
	at nebula.plugin.metrics.dispatcher.AbstractMetricsDispatcher.startUp(AbstractMetricsDispatcher.java:121)
	at nebula.plugin.metrics.com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:55)
	at nebula.plugin.metrics.com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
Tasks to be executed: [task ':appian-android:spoonStandardDebugAndroidTestNonFormsTestSuite4']
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
````

**Comment by FuadBalashov** [comment]
I noticed that the gradle version is 3.5 in the current release of this plugin so I tried version 5.2.0 in addition to 5.3.0.

**Comment by FuadBalashov** [comment]
It looks like manually creating our index fixed the problem.

**Comment by FuadBalashov** [comment]
Though I was able to publish our task data using this plugin I was unable to publish any of our tests data using the plugin. It appears this may be because Android Tests do not extend org.gradle.api.tasks.testing.Test as described in this [SO post](http://stackoverflow.com/questions/38986088/gradle-testlistener-for-connectedandroidtest), any guidance would be appreciated.

**Comment by dvdrlee** [comment]
The problem might be that the plugin currently uses Jest v0.1.7 which does not work with newer version of Elasticsearch (we are on 5.6.2). I was able to get it working by rebuilding the plugin using Jest v2.4.0

**Comment by DanielThomas** [comment]
I'm closing all open issues because we've adopted Gradle Enterprise and we'll be no longer maintaining this plugin. It was already difficult maintaining compatibility due to internal API use, but Gradle 7 and configuration caching will make keeping this working impossible without a rewrite.
