### ISSUE TITLE
Be less paranoid about bubbling up exceptions as logged errors

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-metrics-plugin#7]
Fair to say we get more confusion about connectivity problems to ES, than we do usefulness out of the error messages. We need to suppress these.

**Comment by DanielThomas** [comment]
Looks like this can happen in a couple of places. First during service startup:

```
[metrics] Error while starting metrics dispatcher. Metrics collection disabled.
java.lang.IllegalStateException: Expected the service to be RUNNING, but the service has FAILED
    at nebula.plugin.metrics.com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:285)
    at nebula.plugin.metrics.com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:238)
    at nebula.plugin.metrics.com.google.common.util.concurrent.AbstractExecutionThreadService.awaitRunning(AbstractExecutionThreadService.java:204)
    at nebula.plugin.metrics.collector.GradleCollector.projectsEvaluated(GradleCollector.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:249)
    at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:229)
    at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
    at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:221)
    at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:209)
    at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
    at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
    at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy10.projectsEvaluated(Unknown Source)
    at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:128)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
    at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: nebula.plugin.metrics.org.apache.http.conn.ConnectTimeoutException: Connect failed: connect timed out
    at nebula.plugin.metrics.com.google.common.base.Throwables.propagate(Throwables.java:160)
    at nebula.plugin.metrics.dispatcher.HttpESMetricsDispatcher.execute(HttpESMetricsDispatcher.java:111)
    at nebula.plugin.metrics.dispatcher.HttpESMetricsDispatcher.index(HttpESMetricsDispatcher.java:76)
    at nebula.plugin.metrics.dispatcher.AbstractMetricsDispatcher$3.run(AbstractMetricsDispatcher.java:154)
    at nebula.plugin.metrics.dispatcher.AbstractMetricsDispatcher.execute(AbstractMetricsDispatcher.java:113)
    at nebula.plugin.metrics.dispatcher.AbstractMetricsDispatcher.execute(AbstractMetricsDispatcher.java:45)
    at nebula.plugin.metrics.dispatcher.AbstractQueuedExecutionThreadService.doExecute(AbstractQueuedExecutionThreadService.java:78)
    at nebula.plugin.metrics.dispatcher.AbstractQueuedExecutionThreadService.executeSynchronously(AbstractQueuedExecutionThreadService.java:136)
    at nebula.plugin.metrics.dispatcher.AbstractMetricsDispatcher.indexBuildModel(AbstractMetricsDispatcher.java:163)
    at nebula.plugin.metrics.dispatcher.AbstractMetricsDispatcher.startUp(AbstractMetricsDispatcher.java:125)
    at nebula.plugin.metrics.com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:55)
    at nebula.plugin.metrics.com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
    at java.lang.Thread.run(Thread.java:745)
Caused by: nebula.plugin.metrics.org.apache.http.conn.ConnectTimeoutException: Connect failed: connect timed out
    at nebula.plugin.metrics.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:143)
    at nebula.plugin.metrics.org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
    at nebula.plugin.metrics.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
    at nebula.plugin.metrics.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at nebula.plugin.metrics.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at nebula.plugin.metrics.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at nebula.plugin.metrics.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at nebula.plugin.metrics.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at nebula.plugin.metrics.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at nebula.plugin.metrics.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
    at nebula.plugin.metrics.io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:50)
    at nebula.plugin.metrics.dispatcher.HttpESMetricsDispatcher.execute(HttpESMetricsDispatcher.java:105)
    ... 11 more
Caused by: java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at nebula.plugin.metrics.org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
    at nebula.plugin.metrics.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
    ... 22 more
```

The other is in the base queued execution service.
